### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ninedraft** [centrifugal/protocol#3]
Since there is no license file, go.dev ([link](https://pkg.go.dev/github.com/centrifugal/protocol?tab=overview) to the project page) does not display documentation for this repo. Due to the soon shutdown of godoc.org and to get rid of the uncertainty of the legal status of users of this module, I suggest adding a license file ( MIT? 🙂)

![изображение](https://user-images.githubusercontent.com/12481320/80364461-a7319700-888e-11ea-89e6-6050cb1cb80f.png)

**Comment by FZambia** [comment]
Ah, yeah, must be the same as in Centrifuge library. Also a link to go.dev in README makes sense. Thanks!
