### ISSUE TITLE
Revert deletion of error.go

### ISSUE THREAD

**Issue by maclof** [centrifugal/protocol#6]
You deleted error.go in your last commit and it has broken any builds of the centrifuge-go package 

https://github.com/centrifugal/protocol/blob/40a1cf0b7a8256c9d48b56376683c983a60728b9/error.go

See the related issue I raised here:
https://github.com/centrifugal/centrifuge-go/issues/47

**Comment by FZambia** [comment]
Closing in favour of https://github.com/centrifugal/centrifuge-go/issues/47
